# Generated by Django 4.1.7 on 2023-02-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
