# Generated by Django 4.1.7 on 2023-02-26 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0004_category_cat_image_category_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
