# Generated by Django 4.1.7 on 2023-02-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0006_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
