# Generated by Django 4.1.7 on 2023-02-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0007_rename_product_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
