# Generated by Django 4.1.7 on 2023-02-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0010_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
