# Generated by Django 4.1.7 on 2023-02-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0011_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
