# Generated by Django 4.1.7 on 2023-02-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_customer_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address_line_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_line_2',
        ),
    ]
