# Generated by Django 4.1.7 on 2023-03-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('further_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ABC',
        ),
    ]
