# Generated by Django 4.1.7 on 2023-03-04 14:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_management', '0003_delivarydetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DelivaryDetails',
            new_name='DeliveryDetails',
        ),
    ]
